name: at2someone
version: '1.0.4-SNAPSHOT'
main: top.qixuanjun233.at2someone.At2someone
api-version: '1.20'
authors: [ qixuanjun233 ]
description: 非常fashion的一个@人的tool
website: www.qixuanjun233.top
commands:
  at:
    description: Use this to get information about this plugin
    usage: Type "/at" to get more information
permissions:
  at.mention:
    description: 提及他人权限
    default: true
  at.dnd:
    description: 勿扰模式权限
    default: true
  at.atall:
    description: 提及全体权限
    default: op
  at.admin:
    description: 管理员权限
    default: op